main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h ../../inc/ss_akira.h
aki_ashi.o: aki_ashi.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/ss_akira.h
aki_dou.o: aki_dou.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/ss_akira.h
aki_kao.o: aki_kao.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/ss_akira.h
aki_kata.o: aki_kata.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/ss_akira.h
aki_ude.o: aki_ude.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/ss_akira.h
aki_walk.o: aki_walk.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/ss_akira.h
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sgl_cd.h ../../inc/sega_sys.h
poly.o: poly.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h
poly.o: poly.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sgl_cd.h ../../inc/sega_sys.h
poly.o: poly.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sgl_cd.h ../../inc/sega_sys.h
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sgl_cd.h ../../inc/sega_sys.h
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sgl_cd.h ../../inc/sega_sys.h
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sgl_cd.h ../../inc/sega_sys.h
poly.o: poly.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
poly.o: poly.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sgl_cd.h ../../inc/sega_sys.h
poly.o: poly.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
poly.o: poly.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sgl_cd.h ../../inc/sega_sys.h
poly.o: poly.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sgl_cd.h ../../inc/sega_sys.h
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sgl_cd.h ../../inc/sega_sys.h
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h
poly.o: poly.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
poly.o: poly.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sgl_cd.h ../../inc/sega_sys.h
poly.o: poly.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
poly.o: poly.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sgl_cd.h ../../inc/sega_sys.h
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sgl_cd.h ../../inc/sega_sys.h
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sgl_cd.h ../../inc/sega_sys.h
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sgl_cd.h ../../inc/sega_sys.h
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sgl_cd.h ../../inc/sega_sys.h
poly.o: poly.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
poly.o: poly.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
poly.o: poly.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
poly.o: poly.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h
poly.o: poly.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sgl_cd.h ../../inc/sega_sys.h
poly.o: poly.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sgl_cd.h ../../inc/sega_sys.h
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sgl_cd.h ../../inc/sega_sys.h
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sgl_cd.h ../../inc/sega_sys.h
poly.o: poly.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sgl_cd.h ../../inc/sega_sys.h
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sgl_cd.h ../../inc/sega_sys.h
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sgl_cd.h ../../inc/sega_sys.h
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sgl_cd.h ../../inc/sega_sys.h
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sgl_cd.h ../../inc/sega_sys.h
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sgl_cd.h ../../inc/sega_sys.h
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sgl_cd.h ../../inc/sega_sys.h
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sgl_cd.h ../../inc/sega_sys.h
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sgl_cd.h ../../inc/sega_sys.h
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sgl_cd.h ../../inc/sega_sys.h
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sgl_cd.h ../../inc/sega_sys.h
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sgl_cd.h ../../inc/sega_sys.h
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sgl_cd.h ../../inc/sega_sys.h
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sgl_cd.h ../../inc/sega_sys.h
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sgl_cd.h ../../inc/sega_sys.h
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sgl_cd.h ../../inc/sega_sys.h
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sgl_cd.h ../../inc/sega_sys.h
poly.o: poly.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h
poly.o: poly.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h
poly.o: poly.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sgl_cd.h ../../inc/sega_sys.h
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h
poly.o: poly.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h
poly.o: poly.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sgl_cd.h ../../inc/sega_sys.h
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h
poly.o: poly.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sgl_cd.h ../../inc/sega_sys.h
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sgl_cd.h ../../inc/sega_sys.h
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h
poly.o: poly.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
poly.o: poly.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
poly.o: poly.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sgl_cd.h ../../inc/sega_sys.h
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sgl_cd.h ../../inc/sega_sys.h
poly.o: poly.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
poly.o: poly.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h test.mdl
poly.o: poly.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h mdl_4.mdl
poly.o: poly.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h mdl_3.mdl
poly.o: poly.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h mdl_5.mdl
poly.o: poly.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sgl_cd.h \
 ../../inc/sega_sys.h mdl_6.mdl
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sega_sys.h \
 ../../inc/sega_xpt.h
texture.o: texture.c ../../inc/sgl.h ../../inc/sl_def.h \
 ../../inc/sega_sys.h ../../inc/sega_xpt.h
poly.o: poly.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sega_sys.h \
 ../../inc/sega_xpt.h mdl_6.mdl
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sega_sys.h \
 ../../inc/sega_xpt.h
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sega_sys.h \
 ../../inc/sega_xpt.h
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sega_sys.h \
 ../../inc/sega_xpt.h
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sega_sys.h \
 ../../inc/sega_xpt.h
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sega_sys.h \
 ../../inc/sega_xpt.h
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sega_sys.h \
 ../../inc/sega_xpt.h
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sega_sys.h \
 ../../inc/sega_xpt.h
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sega_sys.h \
 ../../inc/sega_xpt.h
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sega_sys.h \
 ../../inc/sega_xpt.h
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sega_sys.h \
 ../../inc/sega_xpt.h
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sega_sys.h \
 ../../inc/sega_xpt.h
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sega_sys.h \
 ../../inc/sega_xpt.h
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sega_sys.h \
 ../../inc/sega_xpt.h
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sega_sys.h \
 ../../inc/sega_xpt.h
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sega_sys.h \
 ../../inc/sega_xpt.h
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sega_sys.h \
 ../../inc/sega_xpt.h
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sega_sys.h \
 ../../inc/sega_xpt.h
main.o: main.c ../../inc/sgl.h ../../inc/sl_def.h ../../inc/sega_sys.h \
 ../../inc/sega_xpt.h
