/****************************************
*			include files				*
****************************************/
#include	"image.h"

/****************************************
*		declare public objects			*
****************************************/
/*
**	cursor_image[]
**		マウスカーソルのビットマップデータ（16 bit/pixel）
*/
Uint16	cursor_image[CURSOR_WIDTH*CURSOR_HEIGHT] = {
	 VOID,BLACK, VOID, VOID, VOID, VOID, VOID, VOID,
	BLACK,WHITE,BLACK, VOID, VOID, VOID, VOID, VOID,
	BLACK,WHITE,WHITE,BLACK, VOID, VOID, VOID, VOID,
	BLACK,WHITE,WHITE,WHITE,BLACK, VOID, VOID, VOID,
	BLACK,WHITE,WHITE,WHITE,WHITE,BLACK, VOID, VOID,
	BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK, VOID,
	BLACK,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,
	BLACK,WHITE,WHITE,WHITE,WHITE,BLACK,BLACK, VOID,
	BLACK,WHITE,WHITE,BLACK,WHITE,BLACK, VOID, VOID,
	BLACK,WHITE,BLACK,BLACK,WHITE,BLACK, VOID, VOID,
	 VOID,BLACK, VOID, VOID,BLACK,WHITE,BLACK, VOID,
	 VOID, VOID, VOID, VOID,BLACK,WHITE,BLACK, VOID,
	 VOID, VOID, VOID, VOID, VOID,BLACK,WHITE,BLACK,
	 VOID, VOID, VOID, VOID, VOID,BLACK,WHITE,BLACK,
	 VOID, VOID, VOID, VOID, VOID, VOID,BLACK, VOID,
	 VOID, VOID, VOID, VOID, VOID, VOID, VOID, VOID,
};

