#ifndef COMPONENT_TYPES_H
#define COMPONENT_TYPES_H

#define UNUSED_COMPONENT_ID -1

typedef enum
{
    HEALTH_COMPONENT,
    MOVEMENT_COMPONENT,

    COMPONENT_COUNT
} ComponentType;

#endif // !COMPONENT_TYPES_H
