#ifndef HEALTH_MANAGER_H
#define HEALTH_MANAGER_H
#include "ComponentManagerTemplate.h"

COMPONENT_MANAGER_HEADER(Health)

COMPONENT_MANAGER_HEADER(Transform)

COMPONENT_MANAGER_HEADER(Motion)

#endif // !COMPONENT_MANAGERS_H
