/*****************************************************************************
 *
 * Copyright © Sega Europe Ltd. 1995
 *
 * Contents:
 *
 *
 *
 *****************************************************************************
 *
 * $Log$
 *
 ****************************************************************************/

#ifndef _FADE_H_INCLUDED
#define _FADE_H_INCLUDED

/*
 * Include files.
 */


/*
 * #defines and macros.
 */


/*
 * User type and enumerated type definitions.
 */


/*
 * Structure definitions.
 */


/*
 * Function prototypes.
 */
void FadeInit(void);
void FadeDisplay(Sint16 fade_adjust_level);
void FadeToBlack(void);
void FadeFromBlack(void);

/*
 * External variables.
 */


#endif
