/*****************************************************************************
 *
 * Copyright © Sega Europe Ltd. 1995
 *
 * Contents:
 *
 *
 *
 *****************************************************************************
 *
 * $Log$
 *
 ****************************************************************************/

#ifndef _PALETTE_H_INCLUDED
#define _PALETTE_H_INCLUDED

/*
 * Include files.
 */


/*
 * #defines and macros.
 */
#define COLOUR_TRANSPARENT		0
#define COLOUR_LOW_BLUE			1
#define COLOUR_LOW_GREEN		2
#define COLOUR_LOW_CYAN			3
#define COLOUR_LOW_RED			4
#define COLOUR_LOW_MAGENTA		5
#define	COLOUR_LOW_YELLOW		6
#define COLOUR_LOW_WHITE		7
#define COLOUR_GREY				8
#define	COLOUR_GRAY				8
#define COLOUR_BRIGHT_BLUE		9
#define COLOUR_BRIGHT_GREEN		10
#define COLOUR_BRIGHT_CYAN		11
#define COLOUR_BRIGHT_RED		12
#define COLOUR_BRIGHT_MAGENTA	13
#define	COLOUR_BRIGHT_YELLOW	14
#define COLOUR_BRIGHT_WHITE		15


/*
 * User type and enumerated type definitions.
 */


/*
 * Structure definitions.
 */


/*
 * Function prototypes.
 */
void PaletteDefaultSelect(void);


/*
 * External variables.
 */


#endif

