cd S_2_2
copy main.cof ..\..\cof\SLS_22.cof
copy main.abs ..\..\abs\SLS_22.abs
cd ..\S_4_3_1
copy main.cof ..\..\cof\SLS_431.cof
copy main.abs ..\..\abs\SLS_431.abs
cd ..\DEMO_A
copy main.cof ..\..\cof\SLDEMO_A.cof
copy main.abs ..\..\abs\SLDEMO_A.abs
cd ..\DEMO_B
copy main.cof ..\..\cof\SLDEMO_B.cof
copy main.abs ..\..\abs\SLDEMO_B.abs
cd ..\DEMO_C
copy main.cof ..\..\cof\SLDEMO_C.cof
copy main.abs ..\..\abs\SLDEMO_C.abs
cd ..\S_3_2
copy main.cof ..\..\cof\SLS_32.cof
copy main.abs ..\..\abs\SLS_32.abs
cd ..\S_4_2
copy main.cof ..\..\cof\SLS_42.cof
copy main.abs ..\..\abs\SLS_42.abs
cd ..\S_4_3_2
copy main.cof ..\..\cof\SLS_432.cof
copy main.abs ..\..\abs\SLS_432.abs
cd ..\S_4_3_3
copy main.cof ..\..\cof\SLS_433.cof
copy main.abs ..\..\abs\SLS_433.abs
cd ..\S_4_3_4
copy main.cof ..\..\cof\SLS_434.cof
copy main.abs ..\..\abs\SLS_434.abs
cd ..\S_4_5
copy main.cof ..\..\cof\SLS_45.cof
copy main.abs ..\..\abs\SLS_45.abs
cd ..\S_5_2
copy main.cof ..\..\cof\SLS_52.cof
copy main.abs ..\..\abs\SLS_52.abs
cd ..\S_6_3
copy main.cof ..\..\cof\SLS_63.cof
copy main.abs ..\..\abs\SLS_63.abs
cd ..\S_7_2
copy main.cof ..\..\cof\SLS_72.cof
copy main.abs ..\..\abs\SLS_72.abs
cd ..\S_7_4
copy main.cof ..\..\cof\SLS_74.cof
copy main.abs ..\..\abs\SLS_74.abs
cd ..\S_7_6
copy main.cof ..\..\cof\SLS_76.cof
copy main.abs ..\..\abs\SLS_76.abs
cd ..