@echo off
IF EXIST LIB\SEGA_SAT.lib del LIB\SEGA_SAT.lib

REM IF EXIST ADP\*.obj del ADP\*.obj
REM IF EXIST ADP\*.lib del ADP\*.lib
REM IF EXIST LIB\SEGA_ADP.lib del LIB\SEGA_ADP.lib
REM IF EXIST CDC\*.obj del CDC\*.obj
REM IF EXIST CDC\*.lib del CDC\*.lib
REM IF EXIST LIB\SEGA_CDC.lib del LIB\SEGA_CDC.lib
REM IF EXIST PER\*.obj del PER\*.obj
REM IF EXIST PER\*.lib del PER\*.lib
REM IF EXIST LIB\SEGA_PER.lib del LIB\SEGA_PER.lib

IF EXIST BPL\*.obj del BPL\*.obj
IF EXIST BPL\*.lib del BPL\*.lib
IF EXIST LIB\SEGA_BPL.lib del LIB\SEGA_BPL.lib
IF EXIST CMP\*.obj del CMP\*.obj
IF EXIST CMP\*.lib del CMP\*.lib
IF EXIST LIB\SEGA_CMP.lib del LIB\SEGA_CMP.lib
IF EXIST CSH\*.obj del CSH\*.obj
IF EXIST CSH\*.lib del CSH\*.lib
IF EXIST LIB\SEGA_CSH.lib del LIB\SEGA_CSH.lib
IF EXIST DBG\*.obj del DBG\*.obj
IF EXIST DBG\*.lib del DBG\*.lib
IF EXIST LIB\SEGA_DBG.lib del LIB\SEGA_DBG.lib
IF EXIST DMA\*.obj del DMA\*.obj
IF EXIST DMA\*.lib del DMA\*.lib
IF EXIST LIB\SEGA_DMA.lib del LIB\SEGA_DMA.lib
IF EXIST DSP\*.obj del DSP\*.obj
IF EXIST DSP\*.lib del DSP\*.lib
IF EXIST LIB\SEGA_DSP.lib del LIB\SEGA_DSP.lib
IF EXIST GFS\*.obj del GFS\*.obj
IF EXIST GFS\*.lib del GFS\*.lib
IF EXIST LIB\SEGA_GFS.lib del LIB\SEGA_GFS.lib
IF EXIST LIB\SEGADGFS.lib del LIB\SEGADGFS.lib
IF EXIST INT\*.obj del INT\*.obj
IF EXIST INT\*.lib del INT\*.lib
IF EXIST LIB\SEGA_INT.lib del LIB\SEGA_INT.lib
IF EXIST MEM\*.obj del MEM\*.obj
IF EXIST MEM\*.lib del MEM\*.lib
IF EXIST LIB\SEGA_MEM.lib del LIB\SEGA_MEM.lib
IF EXIST MPG\*.obj del MPG\*.obj
IF EXIST MPG\*.lib del MPG\*.lib
IF EXIST LIB\SEGA_MPG.lib del LIB\SEGA_MPG.lib
IF EXIST MTH\*.obj del MTH\*.obj
IF EXIST MTH\*.lib del MTH\*.lib
IF EXIST LIB\SEGA_MTH.lib del LIB\SEGA_MTH.lib
IF EXIST PCM\*.obj del PCM\*.obj
IF EXIST PCM\*.lib del PCM\*.lib
IF EXIST LIB\SEGA_PCM.lib del LIB\SEGA_PCM.lib
IF EXIST SCL\*.obj del SCL\*.obj
IF EXIST SCL\*.lib del SCL\*.lib
IF EXIST LIB\SEGA_SCL.lib del LIB\SEGA_SCL.lib
IF EXIST SND\*.obj del SND\*.obj
IF EXIST SND\*.lib del SND\*.lib
IF EXIST LIB\SEGA_SND.lib del LIB\SEGA_SND.lib
IF EXIST SPR\*.obj del SPR\*.obj
IF EXIST SPR\*.lib del SPR\*.lib
IF EXIST LIB\SEGA_SPR.lib del LIB\SEGA_SPR.lib
IF EXIST STM\*.obj del STM\*.obj
IF EXIST STM\*.lib del STM\*.lib
IF EXIST LIB\SEGA_STM.lib del LIB\SEGA_STM.lib
IF EXIST SYS\*.obj del SYS\*.obj
IF EXIST SYS\*.lib del SYS\*.lib
IF EXIST LIB\SEGA_SYS.lib del LIB\SEGA_SYS.lib
IF EXIST SHC\*.obj del SHC\*.obj
IF EXIST SHC\*.lib del SHC\*.lib
IF EXIST LIB\SEGA_SHC.lib del LIB\SEGA_SHC.lib

