INCLUDE		=

XLIBS		=

#CC		= gcc
CC		= cc

#CFLAGS		= ${INCLUDE} -g -DOW_I18N 
CFLAGS		= ${INCLUDE} -O -DOW_I18N
#CFLAGS		= ${INCLUDE} -g -DOW_I18N -DDEBUG

DEST		= .

ROOT		=

EXTHDRS		=

HDRS		= dgtto3dt.h

INSTALL		= install

#LD		= gcc
LD		= cc

LDFLAGS		=
#LDFLAGS	= -g

LIBS		= -lm
#LIBS		= -lm -lmle

MAKEFILE	= Makefile

OBJS		= main.o tex_red2.o tex_red3.o \
		mat_read.o tex_read.o pix_wrt.o plt_wrt.o ctl_read.o drw_wrt.o

PRINT		= pr

PROGRAM		= dgtto3dt

SHELL		= /bin/sh

SRCS		= main.c tex_red2.c tex_red3.c \
		mat_read.c tex_read.c pix_wrt.c plt_wrt.c ctl_read.c drw_wrt.c


all:		$(PROGRAM)

$(PROGRAM):     $(OBJS)
		@echo "Linking $(PROGRAM) ..."
		@$(LD) $(LDFLAGS) $(OBJS) $(LIBS) -o $(PROGRAM)
		@echo "done"

clean:;		@rm -f $(OBJS) core

clobber:;	@rm -f $(OBJS) $(PROGRAM) core tags

depend:;	@mkmf -f $(MAKEFILE) PROGRAM=$(PROGRAM) DEST=$(DEST)
#depend:;	@mkmf -f $(MAKEFILE) ROOT=$(ROOT)

echo:;		@echo $(HDRS) $(SRCS)

index:;		@ctags -wx $(HDRS) $(SRCS)

install:	$(PROGRAM)
		@echo Installing $(PROGRAM) in $(DEST)
		@-strip $(PROGRAM)
		@if [ $(DEST) != . ]; then \
		(rm -f $(DEST)/$(PROGRAM); $(INSTALL) -f $(DEST) $(PROGRAM)); fi

print:;		@$(PRINT) $(HDRS) $(SRCS)

tags:           $(HDRS) $(SRCS); @ctags $(HDRS) $(SRCS)

update:		$(DEST)/$(PROGRAM)

#$(DEST)/$(PROGRAM): $(SRCS) $(XLIBS) $(HDRS) $(EXTHDRS)
#		@$(MAKE) -f $(MAKEFILE) ROOT=$(ROOT) DEST=$(DEST) install
###
