SET TOOLCHAIN_DIR=%~dp0

SET "TOOLCHAIN_DIR=%TOOLCHAIN_DIR:\=/%"
SET PATH=%TOOLCHAIN_DIR%msys_trimmed/usr/bin;%PATH%

SET YAUL_INSTALL_ROOT=%TOOLCHAIN_DIR%Compiler/sh2eb-elf
SET YAUL_PROG_SH_PREFIX=
SET YAUL_ARCH_SH_PREFIX=sh2eb-elf
SET YAUL_ARCH_M68K_PREFIX=m68keb-elf
SET YAUL_BUILD_ROOT=%TOOLCHAIN_DIR%Libraries/libyaul
SET YAUL_BUILD=build
SET YAUL_CDB=0
SET YAUL_OPTION_DEV_CARTRIDGE=0
SET YAUL_OPTION_MALLOC_IMPL=tlsf
SET YAUL_OPTION_SPIN_ON_ABORT=1
SET YAUL_OPTION_BUILD_GDB=0
SET YAUL_OPTION_BUILD_ASSERT=1
SET SILENT=1
SET MAKE_ISO_XORRISO=%TOOLCHAIN_DIR%msys_trimmed/usr/bin/xorriso

IF NOT EXIST %TOOLCHAIN_DIR%Libraries/libyaul/build/libyaul/release/libyaul.a (
  cd %TOOLCHAIN_DIR%Libraries/
  git clone --recurse-submodules https://github.com/ijacquez/libyaul.git
  cd libyaul
  git checkout 4816a73104b8e5c8a322488f0fc2eabe07ad982a
  make install
)
